# general params
seed: 0

# engineering params
target: "class"
exclude_cols: null
test_size: 0.2
val_size: 0.2

# model params
estimator:
    task: "classification" # or "classification"
    kwargs:
        n_d: 8
        n_a: 8
        n_steps: 3
        gamma: 1.3
        #        cat_idxs: None
        #        cat_dims: None
        #        cat_emb_dim: None
        n_independent: 2
        n_shared: 2
        epsilon: 0.0001
        momentum: 0.02
        lambda_sparse: 0.01
        seed: 0
        clip_value: 1
        verbose: 1
        optimizer_fn: "torch.optim.Adam"
        optimizer_params:
            lr: 0.02
        scheduler_fn: "torch.optim.lr_scheduler.StepLR"
        scheduler_params:
            gamma: 0.95
            step_size: 20
        mask_type: "sparsemax"
        device_name: "auto"
