# general params
seed: 0

# engineering params
target: "class"
exclude_cols: null
test_size: 0.2
val_size: 0.2

# model params
n_decision: 8
n_attention: 8
n_steps: 3
gamma: 1.3
cat_idxs: null
cat_dims: null
cat_emb_dim: null
n_independent: 2
n_shared: 2
epsilon: 1.0e-15
momentum: 0.02
lambda_sparse: 1.0e-3
clip_value: 1
verbose: 1
# optimizer_fn: torch.optim.Adam
# optimizer_params: dict(lr=2e-2)
mask_type: "sparsemax"
device_name: "auto"
